### PR TITLE
Feature/metadata

### PR DESCRIPTION
**Pull request by Npahlfer**
Adds MetaData container.

### CODE REVIEW

**Comment by maeertin** [comment]
Would be nice to go through the tags used and make sure we're up to date with standards.
- Remove Google+ tags
- Keep Twitter tags?
- Add og:product tags?
- Add article template tags?

**Comment by Npahlfer** [comment]
@maeertin I removed the itemProp tags and added some:
* video
* product
* article
* keywords

**Comment by maeertin** [comment]
Hey @vincentboiardt, what do think about this PR? Is the Meta component set up correctly? Should we look into merging it?

One issue that I have is that I can't see any `og:title` printed even though this `<Meta title="Home | Create Oakwood App" />` is being used on the home route.

**Comment by vincentboiardt** [comment]
The Accelerator has a bunch of SEO related components (https://github.com/oakwood/accelerator/tree/master/packages/accelerator/src/components) including `MetaData` (https://github.com/oakwood/accelerator/blob/master/packages/accelerator/src/components/MetaData/index.js)

I think they can stay there instead of in COA.

**Pull request closed without merging**
